<?php
/**
 * Created by PhpStorm.
 * User: wysmacmini02
 * Date: 2019/7/15
 * Time: 18:53
 */
namespace App\Model\Test;

use EasySwoole\Spl\SplBean;

class TestBean extends SplBean
{
    protected $id;
    protected $name;
    protected $code='666666';
    protected $app_secret;
    protected $remark;
    protected $update_time;
    protected $create_time;

    protected function initialize(): void
    {
        $this->create_time = $this->create_time ?? date('Y-m-d H:i:s');
        $this->update_time = $this->update_time ?? date('Y-m-d H:i:s');
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param mixed $id
     */
    public function setId($id): void
    {
        $this->id = $id;
    }

    /**
     * @return mixed
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * @param mixed $name
     */
    public function setName($name): void
    {
        $this->name = $name;
    }

    /**
     * @return string
     */
    public function getCode(): string
    {
        return $this->code;
    }

    /**
     * @param string $code
     */
    public function setCode(string $code): void
    {
        $this->code = $code;
    }

    /**
     * @return mixed
     */
    public function getAppSecret()
    {
        return $this->app_secret;
    }

    /**
     * @param mixed $app_secret
     */
    public function setAppSecret($app_secret): void
    {
        $this->app_secret = $app_secret;
    }

    /**
     * @return mixed
     */
    public function getRemark()
    {
        return $this->remark;
    }

    /**
     * @param mixed $remark
     */
    public function setRemark($remark): void
    {
        $this->remark = $remark;
    }

    /**
     * @return mixed
     */
    public function getUpdateTime()
    {
        return $this->update_time;
    }

    /**
     * @param mixed $update_time
     */
    public function setUpdateTime($update_time): void
    {
        $this->update_time = $update_time;
    }

    /**
     * @return mixed
     */
    public function getCreateTime()
    {
        return $this->create_time;
    }

    /**
     * @param mixed $create_time
     */
    public function setCreateTime($create_time): void
    {
        $this->create_time = $create_time;
    }



}